include:
  # Left (central/master) half: Corne + nice!nano v2 + OLED
  - board: nice_nano_v2
    shield: corne_left nice_oled

  # Right (peripheral) half: Corne + nice!nano v2 + OLED
  - board: nice_nano_v2
    shield: corne_right nice_oled
